//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoCCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Level
    {
        public Level()
        {
            this.TopicOfLevels = new HashSet<TopicOfLevel>();
        }
    
        public string LevelID { get; set; }
        public string LevelName { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<TopicOfLevel> TopicOfLevels { get; set; }
    }
}
