//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoCCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Link
    {
        public Link()
        {
            this.LinkOfMaps = new HashSet<LinkOfMap>();
        }
    
        public string LinkID { get; set; }
        public string ConceptID1 { get; set; }
        public string ConceptID2 { get; set; }
        public string Text { get; set; }
        public Nullable<bool> Result { get; set; }
    
        public virtual ConceptAll ConceptAll { get; set; }
        public virtual ConceptAll ConceptAll1 { get; set; }
        public virtual ICollection<LinkOfMap> LinkOfMaps { get; set; }
    }
}
