//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoCCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public Question()
        {
            this.ConceptForQuestions = new HashSet<ConceptForQuestion>();
            this.QuestionsForTopics = new HashSet<QuestionsForTopic>();
        }
    
        public string QuestionID { get; set; }
        public string QuestionText { get; set; }
    
        public virtual ICollection<ConceptForQuestion> ConceptForQuestions { get; set; }
        public virtual ICollection<QuestionsForTopic> QuestionsForTopics { get; set; }
    }
}
