//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoCCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConceptAll
    {
        public ConceptAll()
        {
            this.ConceptsForTopics = new HashSet<ConceptsForTopic>();
            this.Links = new HashSet<Link>();
            this.Links1 = new HashSet<Link>();
        }
    
        public string ConceptID { get; set; }
        public string ConceptName { get; set; }
    
        public virtual ICollection<ConceptsForTopic> ConceptsForTopics { get; set; }
        public virtual ICollection<Link> Links { get; set; }
        public virtual ICollection<Link> Links1 { get; set; }
    }
}
