//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoCCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LinkOfMap
    {
        public string MapID { get; set; }
        public string LinkID { get; set; }
        public int Stt { get; set; }
    
        public virtual Link Link { get; set; }
        public virtual MapOfUser MapOfUser { get; set; }
    }
}
