//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoCCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionsForTopic
    {
        public string QuestionID { get; set; }
        public string TopicID { get; set; }
        public int Stt { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual Topic Topic { get; set; }
    }
}
