//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoCCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Topic
    {
        public Topic()
        {
            this.ConceptsForTopics = new HashSet<ConceptsForTopic>();
            this.TopicOfLevels = new HashSet<TopicOfLevel>();
        }
    
        public string TopicID { get; set; }
        public string ToppicName { get; set; }
        public string TopicImage { get; set; }
    
        public virtual ICollection<ConceptsForTopic> ConceptsForTopics { get; set; }
        public virtual ICollection<TopicOfLevel> TopicOfLevels { get; set; }
    }
}
